=begin pod

=TITLE role CX::Return

=SUBTITLE Return control exception

    role CX::Next does X::Control { }

A L<control exception|/language/exceptions#Control_exceptions> to be used when
return is called from within a sub; since Rakudo 2019.03, C<throw>ing an
C<X::Control> object raises a control exception which is caught by the L<CONTROL
phaser|/language/phasers#CONTROL> instead of L<CATCH|/language/phasers#CATCH>.

=head1 Methods

=head2 method message

Defined as:

    method message()

Returns "<return control exception>"

=end pod
